---
- name: Update apt-get cache
  apt: update_cache=yes
  tags: common

- include: locale.yml
  tags: 
    - common
    - locale

- name: Install Git
  apt: pkg=git

#- name: Install curl command
#  apt: pkg=curl
#
#- name: Copy .bashrc
#  copy: src=.bashrc dest=/home/{{ user }}/.bashrc
